### ISSUE TITLE
inverse deformation

### ISSUE THREAD

**Issue by luckyxiaoqi** [SZUHvern/TMI_multi-contrast-registration#1]
Why did you choose to construct the inverse transform in this way？ Did it have any basis?

![论文问题](https://user-images.githubusercontent.com/45393819/110439348-4e5b9d80-80f2-11eb-9502-b2e9a7e813be.PNG)

**Comment by SZUHvern** [comment]
We believe that the inverse deformation field obtained in this way should be the most intuitive and direct, which can correspond the deformable field to the registered image through the same deformation. We had compared it with other methods and highlighted the speed advantage of our method.
Of course, since we provide this inverse solution in a direct way to implement, there may still have room for further improvement. We may further improve this idea in the future. Thanks！

**Comment by SZUHvern** [comment]
We believe that the inverse deformation field obtained in this way should be the most intuitive and direct, which can correspond the deformable field to the registered image through the same deformation. We had compared it with other methods and highlighted the speed advantage of our method.

**Comment by luckyxiaoqi** [comment]
Thank  you for your answer.
